### ISSUE TITLE
Closing after tip does not wok

### ISSUE THREAD

**Issue by idrisssystem** [idriss-crypto/tipping-page#1]
**Describe the bug**
Clicking the "Close" button after tipping does not close the page.

**To Reproduce**
1. Go to Twitter
2. Click on send a tip to anyone with a green checkmark
3. Wait for the transaction to be submitted
4. Click "Close" button after successful payment

**Expected behavior**
The window should close and bring you back to Twitter

**Screenshots**
![image](https://user-images.githubusercontent.com/87615244/180850213-31bff442-f3eb-44d8-b0a0-5ad6fb1c174c.png)

**Additional Info**
Reported by [ChouChou](https://discord.com/channels/895318072179716106/962075526586068992/1001028553367896124).

**Comment by matrix0123456789** [comment]
Thank You for noticing. I forgot about this button.

**Comment by idrisssystem** [comment]
Fixed by @matrix0123456789 , thank you!
